### ISSUE TITLE
MissingParameterException

### ISSUE THREAD

**Issue by 956237586** [openedx-unsupported/edx-analytics-pipeline#383]
```
2017-04-23 16:20:38,964 ERROR 24513 [luigi-interface] worker.py:173 - Luigi unexpected framework error while scheduling ModuleEngagem[157/1932]
wTask(source=('hdfs://localhost:9000/data/',), expand_interval=2 days, 0:00:00, pattern=('.*tracking-.*.log.*',), date_pattern=%Y%m%d, warehous
e_path=hdfs://localhost:9000/edx-analytics-pipeline/warehouse/, date=2017-04-23, obfuscate=False, scale_factor=1)
Traceback (most recent call last):
  File "/var/lib/analytics-tasks/analyticstack/venv/local/lib/python2.7/site-packages/luigi/worker.py", line 196, in add
    for next in self._add(current):
  File "/var/lib/analytics-tasks/analyticstack/venv/local/lib/python2.7/site-packages/luigi/worker.py", line 249, in _add
    deps = task.deps()
  File "/var/lib/analytics-tasks/analyticstack/venv/local/lib/python2.7/site-packages/luigi/hadoop.py", line 629, in deps
    return luigi.task.flatten(self.requires_hadoop()) + luigi.task.flatten(self.requires_local())
  File "/var/lib/analytics-tasks/analyticstack/venv/local/lib/python2.7/site-packages/luigi/task.py", line 586, in flatten
    for result in struct:
  File "/var/lib/analytics-tasks/analyticstack/venv/local/lib/python2.7/site-packages/edx/analytics/tasks/insights/module_engagement.py", line 
1216, in requires
    interval_end=self.date
  File "/var/lib/analytics-tasks/analyticstack/venv/local/lib/python2.7/site-packages/luigi/task.py", line 100, in __call__
    param_values = cls.get_param_values(params, args, kwargs)
  File "/var/lib/analytics-tasks/analyticstack/venv/local/lib/python2.7/site-packages/luigi/task.py", line 315, in get_param_values
    raise parameter.MissingParameterException("%s: requires the '%s' parameter to be set" % (exc_desc, param_name))
MissingParameterException: ExternalCourseEnrollmentTableTask[args=(), kwargs={'interval_end': datetime.date(2017, 4, 23)}]: requires the 'overw
rite_n_days' parameter to be set
```

https://github.com/edx/edx-analytics-pipeline/blob/master/edx/analytics/tasks/insights/module_engagement.py#L1216

even i pass overrite_n_days parameter via shell, in above code not pass it to the ExternalCourseEnrollmentTableTask

**Comment by javimudi** [comment]
Ping @nedbat

**Comment by nedbat** [comment]
GitHub issues aren't the way we track problems.  See https://open.edx.org/getting-help for help channels.
